import { ElSwitch } from 'element-plus'
import type { typeColumnList } from '~/types/table'

const data = [
  {
    id: 26,
    brandId: 3,
    productCategoryId: 19,
    feightTemplateId: 0,
    productAttributeCategoryId: 3,
    name: '华为 HUAWEI P20 ',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180607/5ac1bf58Ndefaac16.jpg',
    productSn: '6946605',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 100,
    sale: 100,
    price: 3788,
    promotionPrice: 3659,
    giftGrowth: 3788,
    giftPoint: 3788,
    usePointLimit: 0,
    subTitle: 'AI智慧全面屏 6GB +64GB 亮黑色 全网通版 移动联通电信4G手机 双卡双待手机 双卡双待',
    originalPrice: 4288,
    stock: 1000,
    lowStock: 0,
    unit: '件',
    weight: 0,
    previewStatus: 1,
    serviceIds: '2,3,1',
    keywords: '',
    note: '',
    albumPics: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180607/5ab46a3cN616bdc41.jpg,http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180607/5ac1bf5fN2522b9dc.jpg',
    detailTitle: '',
    promotionStartTime: '2023-01-10T07:49:38.000+00:00',
    promotionEndTime: '2023-01-30T16:00:00.000+00:00',
    promotionPerLimit: 0,
    promotionType: 1,
    brandName: '华为',
    productCategoryName: '手机通讯',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 27,
    brandId: 6,
    productCategoryId: 19,
    feightTemplateId: 0,
    productAttributeCategoryId: 3,
    name: '小米8 全面屏游戏智能手机 6GB+64GB 黑色 全网通4G 双卡双待',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/xiaomi.jpg',
    productSn: '7437788',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 99,
    price: 2699,
    promotionPrice: null,
    giftGrowth: 2699,
    giftPoint: 2699,
    usePointLimit: 0,
    subTitle: '骁龙845处理器，红外人脸解锁，AI变焦双摄，AI语音助手小米6X低至1299，点击抢购',
    originalPrice: 2699,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '1',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 3,
    brandName: '小米',
    productCategoryName: '手机通讯',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 28,
    brandId: 6,
    productCategoryId: 19,
    feightTemplateId: 0,
    productAttributeCategoryId: 3,
    name: '小米 红米5A 全网通版 3GB+32GB 香槟金 移动联通电信4G手机 双卡双待',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5a9d248cN071f4959.jpg',
    productSn: '7437789',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 98,
    price: 649,
    promotionPrice: null,
    giftGrowth: 649,
    giftPoint: 649,
    usePointLimit: 0,
    subTitle: '8天超长待机，137g轻巧机身，高通骁龙处理器小米6X低至1299，点击抢购',
    originalPrice: 649,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 4,
    brandName: '小米',
    productCategoryName: '手机通讯',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 29,
    brandId: 51,
    productCategoryId: 19,
    feightTemplateId: 0,
    productAttributeCategoryId: 3,
    name: 'Apple iPhone 8 Plus 64GB 红色特别版 移动联通电信4G手机',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5acc5248N6a5f81cd.jpg',
    productSn: '7437799',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 97,
    price: 5499,
    promotionPrice: 4799,
    giftGrowth: 5499,
    giftPoint: 5499,
    usePointLimit: 0,
    subTitle: '【限时限量抢购】Apple产品年中狂欢节，好物尽享，美在智慧！速来 >> 勾选[保障服务][原厂保2年]，获得AppleCare+全方位服务计划，原厂延保售后无忧。',
    originalPrice: 5499,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '1,2,3',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: '2020-05-04T07:12:54.000+00:00',
    promotionEndTime: '2020-05-29T16:00:00.000+00:00',
    promotionPerLimit: 0,
    promotionType: 1,
    brandName: '苹果',
    productCategoryName: '手机通讯',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 30,
    brandId: 50,
    productCategoryId: 8,
    feightTemplateId: 0,
    productAttributeCategoryId: 1,
    name: 'HLA海澜之家简约动物印花短袖T恤',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5ad83a4fN6ff67ecd.jpg!cc_350x449.jpg',
    productSn: 'HNTBJ2E042A',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 98,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '2018夏季新品微弹舒适新款短T男生 6月6日-6月20日，满300减30，参与互动赢百元礼券，立即分享赢大奖',
    originalPrice: 98,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: '海澜之家',
    productCategoryName: 'T恤',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 31,
    brandId: 50,
    productCategoryId: 8,
    feightTemplateId: 0,
    productAttributeCategoryId: 1,
    name: 'HLA海澜之家蓝灰花纹圆领针织布短袖T恤',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5ac98b64N70acd82f.jpg!cc_350x449.jpg',
    productSn: 'HNTBJ2E080A',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 98,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '2018夏季新品短袖T恤男HNTBJ2E080A 蓝灰花纹80 175/92A/L80A 蓝灰花纹80 175/92A/L',
    originalPrice: 98,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: '海澜之家',
    productCategoryName: 'T恤',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 32,
    brandId: 50,
    productCategoryId: 8,
    feightTemplateId: 0,
    productAttributeCategoryId: 1,
    name: 'HLA海澜之家短袖T恤男基础款',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5a51eb88Na4797877.jpg',
    productSn: 'HNTBJ2E153A',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 68,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: 'HLA海澜之家短袖T恤男基础款简约圆领HNTBJ2E153A藏青(F3)175/92A(50)',
    originalPrice: 68,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '1,2',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: '海澜之家',
    productCategoryName: 'T恤',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 33,
    brandId: 6,
    productCategoryId: 35,
    feightTemplateId: 0,
    productAttributeCategoryId: 12,
    name: '小米（MI）小米电视4A ',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5b02804dN66004d73.jpg',
    productSn: '4609652',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 2499,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '小米（MI）小米电视4A 55英寸 L55M5-AZ/L55M5-AD 2GB+8GB HDR 4K超高清 人工智能网络液晶平板电视',
    originalPrice: 2499,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: '小米',
    productCategoryName: '电视',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 34,
    brandId: 6,
    productCategoryId: 35,
    feightTemplateId: 0,
    productAttributeCategoryId: 12,
    name: '小米（MI）小米电视4A 65英寸',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5b028530N51eee7d4.jpg',
    productSn: '4609660',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 3999,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: ' L65M5-AZ/L65M5-AD 2GB+8GB HDR 4K超高清 人工智能网络液晶平板电视',
    originalPrice: 3999,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '1,2',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: '小米',
    productCategoryName: '电视',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 35,
    brandId: 58,
    productCategoryId: 29,
    feightTemplateId: 0,
    productAttributeCategoryId: 11,
    name: '耐克NIKE 男子 休闲鞋 ROSHE RUN 运动鞋 511881-010黑色41码',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5b235bb9Nf606460b.jpg',
    productSn: '6799342',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 369,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '耐克NIKE 男子 休闲鞋 ROSHE RUN 运动鞋 511881-010黑色41码',
    originalPrice: 369,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: 'NIKE',
    productCategoryName: '男鞋',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 36,
    brandId: 58,
    productCategoryId: 29,
    feightTemplateId: 0,
    productAttributeCategoryId: 11,
    name: '耐克NIKE 男子 气垫 休闲鞋 AIR MAX 90 ESSENTIAL 运动鞋 AJ1285-101白色41码',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20180615/5b19403eN9f0b3cb8.jpg',
    productSn: '6799345',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 499,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '耐克NIKE 男子 气垫 休闲鞋 AIR MAX 90 ESSENTIAL 运动鞋 AJ1285-101白色41码',
    originalPrice: 499,
    stock: 100,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '',
    keywords: '',
    note: '',
    albumPics: '',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: 'NIKE',
    productCategoryName: '男鞋',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 37,
    brandId: 51,
    productCategoryId: 19,
    feightTemplateId: 0,
    productAttributeCategoryId: 3,
    name: 'Apple iPhone 14 (A2884) 128GB 支持移动联通电信5G 双卡双待手机',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_001.jpg',
    productSn: '100038005189',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 200,
    sale: 0,
    price: 5999,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '【11.11大爱超大爱】指定iPhone14产品限时限量领券立减601元！！！部分iPhone产品现货抢购确认收货即送原厂手机壳10元优惠券！！！猛戳 ',
    originalPrice: 5999,
    stock: 1000,
    lowStock: 0,
    unit: '',
    weight: 208,
    previewStatus: 0,
    serviceIds: '1,2,3',
    keywords: '',
    note: '',
    albumPics: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_002.jpg,http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_003.jpg,http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/iphone14_004.jpg',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: '苹果',
    productCategoryName: '手机通讯',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 38,
    brandId: 51,
    productCategoryId: 53,
    feightTemplateId: 0,
    productAttributeCategoryId: 3,
    name: 'Apple iPad 10.9英寸平板电脑 2022年款',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/ipad_001.jpg',
    productSn: '100044025833',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 3599,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '【11.11大爱超大爱】iPad9代限量抢购，价格优惠，更享以旧换新至高补贴325元！！快来抢购吧！！ ',
    originalPrice: 3599,
    stock: 1000,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '1,2,3',
    keywords: '',
    note: '',
    albumPics: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/ipad_002.jpg',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: '苹果',
    productCategoryName: '平板电脑',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 39,
    brandId: 6,
    productCategoryId: 54,
    feightTemplateId: 0,
    productAttributeCategoryId: 13,
    name: '小米 Xiaomi Book Pro 14 2022 锐龙版 2.8K超清大师屏 高端轻薄笔记本电脑',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_001.jpg',
    productSn: '100023207945',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 5599,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '【双十一大促来袭】指定型号至高优惠1000，以旧换新至高补贴1000元，晒单赢好礼',
    originalPrice: 5599,
    stock: 500,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '',
    keywords: '',
    note: '',
    albumPics: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221028/xiaomi_computer_002.jpg',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 0,
    brandName: '小米',
    productCategoryName: '笔记本',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  },
  {
    id: 40,
    brandId: 6,
    productCategoryId: 19,
    feightTemplateId: 0,
    productAttributeCategoryId: 3,
    name: '小米12 Pro 天玑版 天玑9000+处理器 5000万疾速影像 2K超视感屏 120Hz高刷 67W快充',
    pic: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/xiaomi_12_pro_01.jpg',
    productSn: '100027789721',
    deleteStatus: 0,
    publishStatus: true,
    newStatus: true,
    recommandStatus: true,
    verifyStatus: 0,
    sort: 0,
    sale: 0,
    price: 2999,
    promotionPrice: null,
    giftGrowth: 0,
    giftPoint: 0,
    usePointLimit: 0,
    subTitle: '天玑9000+处理器、5160mAh大电量、2KAmoled超视感屏【点击购买小米11Ultra，戳】 ',
    originalPrice: 2999,
    stock: 500,
    lowStock: 0,
    unit: '',
    weight: 0,
    previewStatus: 0,
    serviceIds: '',
    keywords: '',
    note: '',
    albumPics: 'http://macro-oss.oss-cn-shenzhen.aliyuncs.com/mall/images/20221104/xiaomi_12_pro_02.jpg',
    detailTitle: '',
    promotionStartTime: null,
    promotionEndTime: null,
    promotionPerLimit: 0,
    promotionType: 4,
    brandName: '小米',
    productCategoryName: '手机通讯',
    description: null,
    detailDesc: null,
    detailHtml: null,
    detailMobileHtml: null
  }
]

const columnList: typeColumnList[] = [
  {
    label: '编号',
    value: 'id',
    attr: {
      width: 100,
      align: 'center'
    }
  },
  {
    label: '商品图片',
    value: 'pic',
    attr: {
      width: 120,
      align: 'center'
    },
    renderFn: (row: any) => {
      return <img class="h-80px" src={row.pic} alt="" />
    }
  },
  {
    label: '商品名称',
    value: 'name',
    attr: {
      align: 'center'
    },
    renderFn: (row: any) => {
      return (
        <div>
          <div>{row.name}</div>
          <div>品牌: {row.brandName}</div>
        </div>
      )
    }
  },
  {
    label: '价格/货号',
    value: 'name',
    attr: {
      width: 140,
      align: 'center'
    },
    renderFn: (row: any) => {
      return (
        <div>
          <div>价格: ¥{row.price}</div>
          <div>货号: {row.productSn}</div>
        </div>
      )
    }
  },
  {
    label: '标签',
    value: 'name',
    attr: {
      width: 140,
      align: 'center'
    },
    renderFn: (row: any) => {
      return (
        <div>
          <div>上架: <ElSwitch v-model={row.publishStatus} /></div>
          <div>新品: <ElSwitch v-model={row.newStatus} /></div>
          <div>推荐: <ElSwitch v-model={row.recommandStatus} /></div>
        </div>
      )
    }
  },
  {
    label: '排序',
    value: 'sort',
    attr: {
      width: 100,
      align: 'center'
    }
  },
  {
    label: '销量',
    value: 'sale',
    attr: {
      width: 120,
      align: 'center'
    }
  }
]

export {
  data,
  columnList
}
